name: "Deploy Dev"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/reusable-terraform.yml
    with:
      environment: "dev"
      working_directory: "envs/dev"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}